"""
Core data models for Eleva Decision Engine.

These Pydantic models define the structure of data that flows through
the entire decision cycle:

1. Understand context
2. Observe
3. Detect issues/opportunities
4. Retrieve knowledge
5. Reason (hypotheses)
6. Plan (strategies)
7. Decide
8. Recommend
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from enum import Enum
from pydantic import BaseModel, Field, ConfigDict


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class IssueType(str, Enum):
    PROBLEM = "problem"
    OPPORTUNITY = "opportunity"


class Priority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RecommendationStatus(str, Enum):
    DRAFT = "draft"
    PENDING_APPROVAL = "pending_approval"
    APPROVED = "approved"
    REJECTED = "rejected"


# ---------------------------------------------------------------------------
# 1. Input / Request
# ---------------------------------------------------------------------------

class AnalysisRequest(BaseModel):
    """
    What the user (or system) asks Eleva to analyze.
    This is the entry point of the On Demand mode.
    """
    company_id: str = Field(..., description="Unique identifier of the company")
    question: str = Field(..., description="Natural language question or analysis request")
    focus_areas: Optional[List[str]] = Field(
        default=None,
        description="Optional list of focus areas (e.g. ['churn', 'cart_abandonment'])"
    )
    max_recommendations: int = Field(default=3, ge=1, le=10)


# ---------------------------------------------------------------------------
# 2. Company Context (Understand step)
# ---------------------------------------------------------------------------

class CompanyContext(BaseModel):
    """
    High-level identity and goals of the company.
    Loaded at the beginning of every decision cycle.
    """
    company_id: str
    name: str
    industry: str  # fashion, beauty, food, etc.
    description: Optional[str] = None
    goals: List[str] = Field(default_factory=list)
    current_focus: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# 3. Observation (Observe step)
# ---------------------------------------------------------------------------

class KPI(BaseModel):
    """Single Key Performance Indicator."""
    name: str
    value: float | int | str
    unit: Optional[str] = None
    period: Optional[str] = None  # e.g. "last_30_days"
    trend: Optional[str] = None   # "up", "down", "stable"


class SegmentSummary(BaseModel):
    """Summary of a customer segment."""
    name: str
    size: int
    percentage: float
    key_metrics: Dict[str, Any] = Field(default_factory=dict)


class Observation(BaseModel):
    """
    Everything the agent has observed about the company.
    This is the factual foundation for the rest of the reasoning.
    """
    company_id: str
    observed_at: datetime = Field(default_factory=datetime.utcnow)
    kpis: List[KPI] = Field(default_factory=list)
    segments: List[SegmentSummary] = Field(default_factory=list)
    raw_insights: List[str] = Field(
        default_factory=list,
        description="Human-readable insights extracted during observation"
    )
    data_sources: List[str] = Field(
        default_factory=list,
        description="Which data files / tables were used"
    )
    metadata: Dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# 4. Detection (Detect step)
# ---------------------------------------------------------------------------

class DetectedIssue(BaseModel):
    """
    A problem or opportunity detected by the agent.
    """
    id: str
    type: IssueType
    title: str
    description: str
    priority: Priority = Priority.MEDIUM
    related_kpis: List[str] = Field(default_factory=list)
    evidence: List[str] = Field(
        default_factory=list,
        description="Facts from the Observation that support this issue"
    )


# ---------------------------------------------------------------------------
# 5. Reasoning (Reason step)
# ---------------------------------------------------------------------------

class Hypothesis(BaseModel):
    """
    A possible explanation or approach generated by the agent.
    """
    id: str
    statement: str
    supporting_evidence: List[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, description="0.0 to 1.0")
    related_issue_ids: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# 6. Planning (Plan step)
# ---------------------------------------------------------------------------

class Strategy(BaseModel):
    """
    A concrete strategy the agent is considering.
    """
    id: str
    name: str
    description: str
    related_hypothesis_ids: List[str] = Field(default_factory=list)
    recommended_playbooks: List[str] = Field(
        default_factory=list,
        description="Names of playbooks from the Knowledge Base"
    )
    expected_impact: Optional[str] = None
    effort: Optional[str] = None  # low / medium / high
    risks: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# 7. Final Output (Recommend step)
# ---------------------------------------------------------------------------

class Recommendation(BaseModel):
    """
    The final deliverable of Eleva.
    Clear, justified, and ready for human approval.
    """
    id: str
    company_id: str
    title: str
    summary: str
    justification: str
    priority: Priority = Priority.MEDIUM
    strategies: List[Strategy] = Field(default_factory=list)
    expected_outcomes: List[str] = Field(default_factory=list)
    next_steps: List[str] = Field(default_factory=list)
    status: RecommendationStatus = RecommendationStatus.PENDING_APPROVAL
    created_at: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# 8. Internal State (used by the Decision Engine / LangGraph)
# ---------------------------------------------------------------------------

class DecisionState(BaseModel):
    """
    Full state that travels through the Decision Engine.
    This will later become the LangGraph state.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True)

    request: AnalysisRequest
    company_context: Optional[CompanyContext] = None
    observation: Optional[Observation] = None
    detected_issues: List[DetectedIssue] = Field(default_factory=list)
    retrieved_playbooks: List[Dict[str, Any]] = Field(default_factory=list)
    hypotheses: List[Hypothesis] = Field(default_factory=list)
    strategies: List[Strategy] = Field(default_factory=list)
    recommendations: List[Recommendation] = Field(default_factory=list)
    current_step: str = "understand"
    errors: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)